BEGIN;

DELETE FROM possible_classes
WHERE campus = 'Blacksburg'
  AND term_name = 'Fall 2026'
  AND (
    (subject_code = 'CS' AND course_number IN (2104, 2505))
    OR (subject_code = 'ENGE' AND course_number = 1414)
    OR (subject_code = 'MATH' AND course_number = 2114)
  );

WITH raw_sections (
    campus,
    term_name,
    crn,
    subject_code,
    course_number,
    course_suffix,
    is_honors,
    course_title,
    section_code,
    credits,
    schedule_type,
    modality,
    seats_available,
    capacity,
    availability_status,
    instructor_name,
    instructor_rating,
    raw_days,
    begin_time_raw,
    end_time_raw,
    location_raw,
    building,
    room,
    exam_code,
    comments_text,
    restriction_level,
    requires_transfer_status,
    requires_math_major,
    requires_special_approval,
    requires_laptop,
    requires_software_bundle,
    min_completed_credit_hours,
    required_completed_courses,
    eligibility_rules
) AS (
VALUES
    ('Blacksburg', 'Fall 2026', '83519', 'CS', 2104, NULL, FALSE, 'Intro to Problem Solving in CS', '83519', 3, 'L', 'Face-to-Face Instruction', 81, 90, 'open', 'MO Ellis', NULL::numeric, 'M W F', '11:15AM', '12:05PM', 'NCB 120', 'NCB', '120', '11M', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '83520', 'CS', 2104, NULL, FALSE, 'Intro to Problem Solving in CS', '83520', 3, 'L', 'Face-to-Face Instruction', 85, 90, 'open', 'MO Ellis', NULL::numeric, 'M W F', '10:10AM', '11:00AM', 'NCB 120', 'NCB', '120', '10M', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '83521', 'CS', 2104, NULL, FALSE, 'Intro to Problem Solving in CS', '83521', 3, 'L', 'Face-to-Face Instruction', 81, 90, 'open', 'O Emebo', NULL::numeric, 'M W F', '9:05AM', '9:55AM', 'NCB 120', 'NCB', '120', '09M', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '83522', 'CS', 2104, NULL, FALSE, 'Intro to Problem Solving in CS', '83522', 3, 'L', 'Face-to-Face Instruction', 83, 90, 'open', 'O Emebo', NULL::numeric, 'M W F', '1:25PM', '2:15PM', 'NCB 120', 'NCB', '120', '13M', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '83523', 'CS', 2104, NULL, FALSE, 'Intro to Problem Solving in CS', '83523', 3, 'L', 'Face-to-Face Instruction', 74, 90, 'open', 'SB Nizamani', NULL::numeric, 'T R', '2:00PM', '3:15PM', 'NCB 120', 'NCB', '120', '14T', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '83545', 'CS', 2505, NULL, FALSE, 'Intro Computer Organization', '83545', 3, 'L', 'Face-to-Face Instruction', 140, 175, 'open', 'DP McPherson', NULL::numeric, 'T R', '2:00PM', '3:15PM', 'WHIT 300', 'WHIT', '300', 'CTE', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '83546', 'CS', 2505, NULL, FALSE, 'Intro Computer Organization', '83546', 3, 'L', 'Face-to-Face Instruction', 165, 175, 'open', 'S Cao', NULL::numeric, 'T R', '11:00AM', '12:15PM', 'WHIT 300', 'WHIT', '300', 'CTE', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '83547', 'CS', 2505, NULL, FALSE, 'Intro Computer Organization', '83547', 3, 'L', 'Face-to-Face Instruction', 149, 175, 'open', 'S Cao', NULL::numeric, 'T R', '8:00AM', '9:15AM', 'STEG N 145', 'STEG N', '145', 'CTE', 'Students outside the major should not assume completion of this course will affect or assure their ability to change into this major or waive major-restrictions for future courses in this department.', 'soft', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"major_change_advisory","hard":false}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '85184', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '85184', 4, 'B', 'Face-to-Face Instruction', 72, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '8:00AM', '9:15AM', 'GOODW 115', 'GOODW', '115', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '85185', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '85185', 4, 'B', 'Face-to-Face Instruction', 71, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '9:30AM', '10:45AM', 'GOODW 115', 'GOODW', '115', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '85186', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '85186', 4, 'B', 'Face-to-Face Instruction', 72, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '11:00AM', '12:15PM', 'GOODW 155', 'GOODW', '155', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '85187', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '85187', 4, 'B', 'Face-to-Face Instruction', 68, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '12:30PM', '1:45PM', 'GOODW 155', 'GOODW', '155', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped. This section is reserved for Transfer Students.', 'hard', TRUE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true},{"type":"transfer_students_only","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '85188', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '85188', 4, 'B', 'Face-to-Face Instruction', 70, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '2:00PM', '3:15PM', 'GOODW 155', 'GOODW', '155', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '85189', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '85189', 4, 'B', 'Face-to-Face Instruction', 68, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '3:30PM', '4:45PM', 'GOODW 155', 'GOODW', '155', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped. This section is reserved for Transfer Students.', 'hard', TRUE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true},{"type":"transfer_students_only","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '85190', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '85190', 4, 'B', 'Face-to-Face Instruction', 72, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '5:30PM', '6:45PM', 'GOODW 115', 'GOODW', '115', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '91108', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '91108', 4, 'B', 'Face-to-Face Instruction', 72, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '11:00AM', '12:15PM', 'GOODW 115', 'GOODW', '115', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '91109', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '91109', 4, 'B', 'Face-to-Face Instruction', 72, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '4:00PM', '5:15PM', 'GOODW 115', 'GOODW', '115', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '91110', 'ENGE', 1414, NULL, FALSE, 'Foundations of Engr Practice', '91110', 4, 'B', 'Face-to-Face Instruction', 72, 72, 'open', 'Staff', NULL::numeric, 'M T W R', '5:30PM', '6:45PM', 'GOODW 155', 'GOODW', '155', '00X', 'Laptop or 2-in-1 tablet meeting COE specifications required; must purchase Engineering Software bundle. Completion of this course will not guarantee the ability to change into a degree-granting engineering major or waive major-restrictions for future courses. Students must have earned credit for the following courses to be eligible for ENGE 1414: (ENGL 1105), (MATH 1225 and MATH 1226), and 19 credit hours. Students not meeting the pre-requisites will be dropped.', 'hard', FALSE, FALSE, FALSE, TRUE, TRUE, 19, ARRAY['ENGL 1105', 'MATH 1225', 'MATH 1226']::TEXT[], '[{"type":"completed_courses_all","courses":["ENGL 1105","MATH 1225","MATH 1226"]},{"type":"min_completed_credit_hours","value":19},{"type":"laptop_required","value":true},{"type":"software_bundle_required","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87551', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87551', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'T R', '2:00PM', '3:15PM', 'USLB 212', 'USLB', '212', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87552', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87552', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'T R', '9:30AM', '10:45AM', 'WLH 345', 'WLH', '345', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87553', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87553', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'M W F', '11:15AM', '12:05PM', 'LITRV 1800', 'LITRV', '1800', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87554', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87554', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'T R', '8:00AM', '9:15AM', 'MCB 307', 'MCB', '307', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87555', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87555', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'M W F', '9:05AM', '9:55AM', 'PAM 1004', 'PAM', '1004', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87556', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87556', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'M W F', '1:25PM', '2:15PM', 'USLB 312', 'USLB', '312', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87557', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87557', 3, 'L', 'Face-to-Face Instruction', 6, 35, 'open', 'Staff', NULL::numeric, 'T R', '9:30AM', '10:45AM', 'MCB 232', 'MCB', '232', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87558', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87558', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'T R', '3:30PM', '4:45PM', 'MCB 232', 'MCB', '232', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87559', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87559', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'T R', '11:00AM', '12:15PM', 'WLH 345', 'WLH', '345', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87560', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87560', 3, 'L', 'Face-to-Face Instruction', 1, 35, 'open', 'Staff', NULL::numeric, 'M W F', '12:20PM', '1:10PM', 'MCB 232', 'MCB', '232', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87561', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87561', 3, 'L', 'Face-to-Face Instruction', 27, 35, 'open', 'S Gugercin', NULL::numeric, 'M W', '4:00PM', '5:15PM', 'PAM 3028', 'PAM', '3028', 'CTE', 'This section is intended for Math Majors only.', 'hard', FALSE, TRUE, FALSE, FALSE, FALSE, NULL, NULL, '[{"type":"math_majors_only","value":true}]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87562', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87562', 3, 'L', 'Face-to-Face Instruction', 21, 35, 'open', 'Staff', NULL::numeric, 'T R', '5:00PM', '6:15PM', 'MCB 307', 'MCB', '307', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87563', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87563', 3, 'L', 'Face-to-Face Instruction', 33, 35, 'open', 'Staff', NULL::numeric, 'M W F', '9:05AM', '9:55AM', 'WLH 335', 'WLH', '335', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87564', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87564', 3, 'L', 'Face-to-Face Instruction', 17, 35, 'open', 'Staff', NULL::numeric, 'M W F', '1:25PM', '2:15PM', 'ROB 103', 'ROB', '103', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87565', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87565', 3, 'L', 'Face-to-Face Instruction', 21, 35, 'open', 'Staff', NULL::numeric, 'T R', '11:00AM', '12:15PM', 'LITRV 1800', 'LITRV', '1800', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87567', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87567', 3, 'L', 'Face-to-Face Instruction', 32, 35, 'open', 'Staff', NULL::numeric, 'T R', '8:00AM', '9:15AM', 'PAM 1008', 'PAM', '1008', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87569', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87569', 3, 'L', 'Face-to-Face Instruction', 34, 35, 'open', 'Staff', NULL::numeric, 'M W F', '8:00AM', '8:50AM', 'PAM 2028', 'PAM', '2028', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87570', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87570', 3, 'L', 'Face-to-Face Instruction', 24, 35, 'open', 'Staff', NULL::numeric, 'M W F', '9:05AM', '9:55AM', 'MCB 232', 'MCB', '232', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87571', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87571', 3, 'L', 'Face-to-Face Instruction', 0, 35, 'full', 'Staff', NULL::numeric, 'T R', '12:30PM', '1:45PM', 'ROB 103', 'ROB', '103', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87572', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87572', 3, 'L', 'Face-to-Face Instruction', 19, 35, 'open', 'Staff', NULL::numeric, 'T R', '11:00AM', '12:15PM', 'MCB 126', 'MCB', '126', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87573', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87573', 3, 'L', 'Face-to-Face Instruction', 21, 35, 'open', 'Staff', NULL::numeric, 'M W F', '10:10AM', '11:00AM', 'PAM 1004', 'PAM', '1004', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87574', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87574', 3, 'L', 'Face-to-Face Instruction', 19, 35, 'open', 'Staff', NULL::numeric, 'T R', '12:30PM', '1:45PM', 'MCB 224', 'MCB', '224', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87575', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87575', 3, 'L', 'Face-to-Face Instruction', 30, 35, 'open', 'Staff', NULL::numeric, 'M W F', '12:20PM', '1:10PM', 'PAM 1004', 'PAM', '1004', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87576', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87576', 3, 'L', 'Face-to-Face Instruction', 26, 35, 'open', 'Staff', NULL::numeric, 'M W F', '11:15AM', '12:05PM', 'MCB 232', 'MCB', '232', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87577', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87577', 3, 'L', 'Face-to-Face Instruction', 26, 35, 'open', 'Staff', NULL::numeric, 'T R', '11:00AM', '12:15PM', 'MCB 231', 'MCB', '231', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87578', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87578', 3, 'L', 'Face-to-Face Instruction', 27, 35, 'open', 'Staff', NULL::numeric, 'M W F', '10:10AM', '11:00AM', 'PAM 1003', 'PAM', '1003', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87579', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87579', 3, 'L', 'Face-to-Face Instruction', 24, 35, 'open', 'Staff', NULL::numeric, 'T R', '2:00PM', '3:15PM', 'MCB 321', 'MCB', '321', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87580', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87580', 3, 'L', 'Face-to-Face Instruction', 22, 35, 'open', 'Staff', NULL::numeric, 'M W F', '1:25PM', '2:15PM', 'WLH 335', 'WLH', '335', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87581', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87581', 3, 'L', 'Face-to-Face Instruction', 24, 35, 'open', 'Staff', NULL::numeric, 'M W F', '10:10AM', '11:00AM', 'PAT 215', 'PAT', '215', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87582', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87582', 3, 'L', 'Face-to-Face Instruction', 16, 35, 'open', 'Staff', NULL::numeric, 'M W F', '11:15AM', '12:05PM', 'PAM 3004', 'PAM', '3004', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87583', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87583', 3, 'L', 'Face-to-Face Instruction', 30, 35, 'open', 'Staff', NULL::numeric, 'M W F', '1:25PM', '2:15PM', 'ROB 112', 'ROB', '112', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87584', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87584', 3, 'L', 'Face-to-Face Instruction', 30, 40, 'open', 'Staff', NULL::numeric, 'M W', '4:00PM', '5:15PM', 'GBJ 102', 'GBJ', '102', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87585', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87585', 3, 'L', 'Face-to-Face Instruction', 30, 35, 'open', 'Staff', NULL::numeric, 'M W', '4:00PM', '5:15PM', 'AA 114', 'AA', '114', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87586', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '87586', 3, 'L', 'Face-to-Face Instruction', 23, 35, 'open', 'Staff', NULL::numeric, 'M W F', '2:30PM', '3:20PM', 'PAM 1008', 'PAM', '1008', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '91645', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '91645', 3, 'L', 'Face-to-Face Instruction', 31, 35, 'open', 'Staff', NULL::numeric, 'M W F', '2:30PM', '3:20PM', 'PAM 1003', 'PAM', '1003', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '91646', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '91646', 3, 'L', 'Face-to-Face Instruction', 28, 35, 'open', 'Staff', NULL::numeric, 'M W F', '12:20PM', '1:10PM', 'LITRV 1800', 'LITRV', '1800', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '91648', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '91648', 3, 'L', 'Face-to-Face Instruction', 31, 35, 'open', 'Staff', NULL::numeric, 'T R', '2:00PM', '3:15PM', 'HUTCH 204', 'HUTCH', '204', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '92318', 'MATH', 2114, NULL, FALSE, 'Introduction to Linear Algebra', '92318', 3, 'L', 'Face-to-Face Instruction', 160, 160, 'open', 'Staff', NULL::numeric, 'T R', '5:00PM', '6:15PM', 'WHIT 300', 'WHIT', '300', 'CTE', NULL, 'none', FALSE, FALSE, FALSE, FALSE, FALSE, NULL, NULL, '[]'::jsonb),
    ('Blacksburg', 'Fall 2026', '87589', 'MATH', 2114, 'H', TRUE, 'Introduction to Linear Algebra', '87589', 3, 'L', 'Face-to-Face Instruction', 24, 30, 'open', 'F Rabby', NULL::numeric, 'T R', '9:30AM', '10:45AM', 'MCB 134', 'MCB', '134', 'CTE', 'This course is open to students who are not in the Honors College on a case-by-case basis. For more information: https://www.math.vt.edu/honors', 'soft', FALSE, FALSE, TRUE, FALSE, FALSE, NULL, NULL, '[{"type":"special_approval_may_be_required","value":true}]'::jsonb)
),
expanded AS (
    SELECT
        campus,
        term_name,
        crn,
        subject_code,
        course_number,
        course_suffix,
        is_honors,
        course_title,
        section_code,
        credits,
        schedule_type,
        modality,
        seats_available,
        capacity,
        availability_status,
        instructor_name,
        instructor_rating,
        raw_days,
        CASE day_code
            WHEN 'M' THEN 'Mon'
            WHEN 'T' THEN 'Tue'
            WHEN 'W' THEN 'Wed'
            WHEN 'R' THEN 'Thu'
            WHEN 'F' THEN 'Fri'
            WHEN 'S' THEN 'Sat'
        END AS day_of_week,
        to_timestamp(begin_time_raw, 'HH12:MIAM')::time AS start_time,
        to_timestamp(end_time_raw, 'HH12:MIAM')::time AS end_time,
        location_raw,
        building,
        room,
        exam_code,
        comments_text,
        restriction_level,
        requires_transfer_status,
        requires_math_major,
        requires_special_approval,
        requires_laptop,
        requires_software_bundle,
        min_completed_credit_hours,
        required_completed_courses,
        eligibility_rules
    FROM raw_sections
    CROSS JOIN LATERAL regexp_split_to_table(raw_days, '\s+') AS day_code
)
INSERT INTO possible_classes (
    campus,
    term_name,
    crn,
    subject_code,
    course_number,
    course_suffix,
    is_honors,
    course_title,
    section_code,
    credits,
    schedule_type,
    modality,
    seats_available,
    capacity,
    availability_status,
    instructor_name,
    instructor_rating,
    raw_days,
    day_of_week,
    start_time,
    end_time,
    location_raw,
    building,
    room,
    exam_code,
    comments_text,
    restriction_level,
    requires_transfer_status,
    requires_math_major,
    requires_special_approval,
    requires_laptop,
    requires_software_bundle,
    min_completed_credit_hours,
    required_completed_courses,
    eligibility_rules
)
SELECT
    campus,
    term_name,
    crn,
    subject_code,
    course_number,
    course_suffix,
    is_honors,
    course_title,
    section_code,
    credits,
    schedule_type,
    modality,
    seats_available,
    capacity,
    availability_status,
    instructor_name,
    instructor_rating,
    raw_days,
    day_of_week,
    start_time,
    end_time,
    location_raw,
    building,
    room,
    exam_code,
    comments_text,
    restriction_level,
    requires_transfer_status,
    requires_math_major,
    requires_special_approval,
    requires_laptop,
    requires_software_bundle,
    min_completed_credit_hours,
    required_completed_courses,
    eligibility_rules
FROM expanded
ON CONFLICT (term_name, crn, day_of_week, start_time, end_time)
DO UPDATE SET
    campus = EXCLUDED.campus,
    subject_code = EXCLUDED.subject_code,
    course_number = EXCLUDED.course_number,
    course_suffix = EXCLUDED.course_suffix,
    is_honors = EXCLUDED.is_honors,
    course_title = EXCLUDED.course_title,
    section_code = EXCLUDED.section_code,
    credits = EXCLUDED.credits,
    schedule_type = EXCLUDED.schedule_type,
    modality = EXCLUDED.modality,
    seats_available = EXCLUDED.seats_available,
    capacity = EXCLUDED.capacity,
    availability_status = EXCLUDED.availability_status,
    instructor_name = EXCLUDED.instructor_name,
    instructor_rating = EXCLUDED.instructor_rating,
    raw_days = EXCLUDED.raw_days,
    location_raw = EXCLUDED.location_raw,
    building = EXCLUDED.building,
    room = EXCLUDED.room,
    exam_code = EXCLUDED.exam_code,
    comments_text = EXCLUDED.comments_text,
    restriction_level = EXCLUDED.restriction_level,
    requires_transfer_status = EXCLUDED.requires_transfer_status,
    requires_math_major = EXCLUDED.requires_math_major,
    requires_special_approval = EXCLUDED.requires_special_approval,
    requires_laptop = EXCLUDED.requires_laptop,
    requires_software_bundle = EXCLUDED.requires_software_bundle,
    min_completed_credit_hours = EXCLUDED.min_completed_credit_hours,
    required_completed_courses = EXCLUDED.required_completed_courses,
    eligibility_rules = EXCLUDED.eligibility_rules;

COMMIT;
